Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/pharma.com/msp

  - &Cipla
    Name: CiplaMSP
    ID: CiplaMSP
    MSPDir: ../organizations/peerOrganizations/cipla.pharma.com/msp

  - &Medlife
    Name: MedlifeMSP
    ID: MedlifeMSP
    MSPDir: ../organizations/peerOrganizations/medlife.pharma.com/msp

  - &Apollo
    Name: ApolloMSP
    ID: ApolloMSP
    MSPDir: ../organizations/peerOrganizations/apollo.pharma.com/msp

  - &CDSCO
    Name: CDSCOMSP
    ID: CDSCOMSP
    MSPDir: ../organizations/peerOrganizations/cdsco.pharma.com/msp

Profiles:
  PharmaChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Cipla
        - *Medlife
        - *Apollo
        - *CDSCO
